import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Header from '@/app/appComponents/Header'
import Footer from '@/app/appComponents/Footer'
import AppSidebar from '@/app/appComponents/AppSidebar'
import {
  SidebarProvider,
  SidebarInset,
  SidebarTrigger
} from '@/components/ui/sidebar'


const geist = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />

          <SidebarInset className="p-5">
            {children}
          </SidebarInset>

        </SidebarProvider>

      </body>
    </html>
  );
}
